name: update-dotnet-sdk

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    name: Update .NET SDK
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update .NET SDK
      uses: martincostello/update-dotnet-sdk@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        user-email: martin@martincostello.com
        user-name: martincostello
